name: Build Android APKs (split-per-abi) and Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: Tag name to create/use for the release (e.g., v1.2.3)
        required: true
        type: string
      release_name:
        description: Optional release title (defaults to tag)
        required: false
        type: string
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build split-per-abi APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Fetch dependencies
        run: flutter pub get

      - name: Build split-per-abi APKs (release)
        run: flutter build apk --release --split-per-abi

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-split
          path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-apk-split
          path: dist

      - name: Set release variables
        id: vars
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.release_tag }}"
            NAME="${{ github.event.inputs.release_name }}"
            if [ -z "$NAME" ]; then NAME="$TAG"; fi
          else
            TAG="${{ github.ref_name }}"
            NAME="${{ github.ref_name }}"
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "name=$NAME" >> "$GITHUB_OUTPUT"

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: ${{ steps.vars.outputs.name }}
          draft: false
          prerelease: false
          files: |
            dist/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
